#%RAML 1.0 DataType
types: 
    categoriesResponseType:
    description: categoryid
    type: object
    properties:
      categoryid:
        description: 
        type: integer
        required: true
        example: 1
      name:
        description: 
        type: string
        required: true
        example: "nega"