#%RAML 1.0 Library
usage: champ-onlineshop DataType
types: 
    categoriesResponseType:
    type: object
    properties:
        categoryid:
        description: 
        type: integer
        example: 1